// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5588.Feodora.commands;
import org.usfirst.frc5588.Feodora.Robot;

import edu.wpi.first.wpilibj.command.Command;
/**
 *
 */
public class ClimberCommand extends Command {

    public ClimberCommand() {
        requires(Robot.climber);
    }

	protected void initialize() {
	}

	protected void execute() {
		//don't want climber to go the wrong direction
		double fSpeed = deadzone(Robot.oi.manipulatorJoystick.getRawAxis(1));
		if(fSpeed>0)
		{
			Robot.climber.setSpeed(0);
		}
		else
			Robot.climber.setSpeed(-fSpeed);
	}
	
	private double deadzone(double in){
    	if(Math.abs(in)<0.2)
    		return 0.0;
    	return in;
	}

	protected boolean isFinished() {
		return false;
	}

	protected void end() {
		Robot.climber.setSpeed(0.0);
	}

	protected void interrupted() {
		end();
	}
}