
package org.usfirst.frc5588.Feodora;

import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;


public class RobotMap {
    
    public static SpeedController driveLeftDrive;
    public static SpeedController driveRightDrive;
    public static SpeedController climberMotor;
    public static Encoder leftEncoder;
    public static Encoder rightEncoder;
    //gracie gyroscope code
    //public static AnalogGyro gyroscope;
    public static final int CAMERA_FORWARDS = 1;


    public static void init() {
        
        driveLeftDrive = new Victor(2);
        
        driveRightDrive = new Victor(0);
        
        //When using the competition bot (Victoria), use the talon climber motor.
        climberMotor = new Talon(4);
        
        //When using the backup bot (Feodora), use the victor climber motor.
        //climberMotor = new Victor(4);
        
        leftEncoder = new Encoder(2, 3);
        
        rightEncoder = new Encoder(0,1);
    }
}
